import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import InfoText from "./block/infoText";

const inter = Inter({ subsets: ["latin"] });

type menulistType = {
  name: string[];
};

type menuType = {
  key: string;
  menuname: string;
};

export default function Home() {
  const menus = ["개발자", "레퍼런스", "건의사항"];

  function MenuItem(props: menuType) {
    return <span className={styles.menuname}>{props.menuname}</span>;
  }

  function MenuList(props: menulistType) {
    const listItems = props.name.map((one, idx) => {
      return <MenuItem key={idx.toString()} menuname={one} />;
    });
    return <div className={styles.menulist}>{listItems}</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MenuList name={menus} />
        <div className={styles.mainin}>
          <InfoText />
        </div>
      </main>
    </>
  );
}
